import React from 'react';
import './page.css';
import Separator from '../../../../Components/Orange-separator/separator';

function AerosolIntro() {
  return (
    <>
        <div className='Aerosol_container'>
            <p>
                Aerosol Capture
            </p>
            <h1>
                Aerosol Separation and Capture
            </h1>
            <img src={`${process.env.PUBLIC_URL}/images/CaptureMain.png`} alt='microscope' width='100%' height="100%"/>
            <div className='text-after-capture-robot'>
                <p>
                    Understanding and addressing the issues related to aerosol particles are challenging in terrestrial applications as well as on various planetary bodies. ASP is developing technologies focused on dust mitigation, aerosol capture and aerosol characterization.
                </p>
                <p>
                    ASP’s <a href='dust-mitigation'>media-free dust filtration system</a> removes aerosolized particulates from air in confined spaces such as spacecraft cabins. This filter is aimed at combating the effects of dust generated by crew activities like exercising and cleaning within the spacecraft, as well as the dust that may enter the spacecraft after the crew extravehicular activities on the surfaces of Mars and the moon. Since it relies on electrostatic, electrodynamic and fluid dynamic forces, our technology does not need replacement filters and has lower power requirement than the HEPA filters that are commonly used in such applications. 
                </p>
            </div>
            <Separator />
            <div className='capture-collection-images'>
                <img src={`${process.env.PUBLIC_URL}/images/marsCloseUpRocks.png`} alt='rocks' width='48.94%' height="50%"/>
                <img src={`${process.env.PUBLIC_URL}/images/marsCloseUp2.png`} alt='mars2' width='48.94%' height="50%"/>
                <img src={`${process.env.PUBLIC_URL}/images/FUGG.png`} alt='FUGGING FUGG' width='100%' height="100%"/>
            </div>
        </div>
    </>
  )
}

export default AerosolIntro
