import React from 'react';
import './page.css';

function AerosolIntro() {
  return (
    <>
        <div className='Aerosol_img_container'>
            <div className='Aerosol_intro_text'>
                <h1>Aerosol Separation and Capture</h1>
            </div>
        </div>
        <div className='Aerosol_intro'>
            <div className='Aerosol_separator'/>
            <div className='Aerosol_intro_container'>
                <p>Understanding and addressing the issues related to aerosol particles are challenging in terrestrial applications as well as on various planetary bodies. ASP is developing technologies focused on dust mitigation, aerosol capture and aerosol characterization.</p>
                <p>ASP’s  <a href="/dust-mitigation">media-free dust filtration system</a> removes aerosolized particulates from air in confined spaces such as spacecraft cabins. This filter is aimed at combating the effects of dust generated by crew activities like exercising and cleaning within the spacecraft, as well as the dust that may enter the spacecraft after the crew extravehicular activities on the surfaces of Mars and the moon. Since it relies on electrostatic, electrodynamic and fluid dynamic forces, our technology does not need replacement filters and has lower power requirement than the HEPA filters that are commonly used in such applications.</p>
                <p>By removing the dust particles, our media-free filter improves the air quality for the crew and extends the life of process equipment such as oxygen generators. Our surface dust mitigation technology uses a combination of mechanical and electrical forces to prevent dust particles from collecting on key components such as optical surfaces, radiators, and dust sensitive equipment.</p>
            </div>
        </div>
    </>
  )
}

export default AerosolIntro
