name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Check out the code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'  # Adjust Node version as needed

      - name: Install dependencies
        run: npm install

      - name: Build the project
        run: npm run build  # Generates the static site in the 'out' directory

      - name: Deploy to GitHub Pages
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"
          mv out/* .   # Move contents of 'out' to the root if pushing to 'gh-pages'
          git add -f .
          git commit -m "Deploy to GitHub Pages"
          git push origin +gh-pages  # Force push to 'gh-pages' branch
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
